package mypace.rules_engine_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Lifestyle Disease")
	private java.lang.String lifestyleDisease;
	@org.kie.api.definition.type.Label("RecommendedPlan")
	private java.lang.String recommendedPlan;

	@org.kie.api.definition.type.Label(value = "weight")
	private java.lang.Integer weight;

	public Patient() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getLifestyleDisease() {
		return this.lifestyleDisease;
	}

	public void setLifestyleDisease(java.lang.String lifestyleDisease) {
		this.lifestyleDisease = lifestyleDisease;
	}

	public java.lang.String getRecommendedPlan() {
		return this.recommendedPlan;
	}

	public void setRecommendedPlan(java.lang.String recommendedPlan) {
		this.recommendedPlan = recommendedPlan;
	}

	public java.lang.Integer getWeight() {
		return this.weight;
	}

	public void setWeight(java.lang.Integer weight) {
		this.weight = weight;
	}

	public Patient(java.lang.String name, java.lang.String lifestyleDisease,
			java.lang.String recommendedPlan, java.lang.Integer weight) {
		this.name = name;
		this.lifestyleDisease = lifestyleDisease;
		this.recommendedPlan = recommendedPlan;
		this.weight = weight;
	}

}